version: "3.9"

services:
  web:
    build: ./timetable_app
    command: gunicorn timetable.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - ./rtu_timetable_api/output:/code/timetable_app/db
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev

  api:
    build: ./rtu_timetable_api
    command: bash -c "ls && python main.py"
    volumes:
      - ./rtu_timetable_api:/code
      - ./rtu_timetable_api/output:/code/output
    ports:
      - "5000:8000"
    env_file:
      - ./env.dev
    depends_on:
      - web

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./env.dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert:/certs:ro
      - ./timetable_app/timetable_app/static:/data/static
      - ./timetable_app/timetable_app/media:/data/media
      - ./logs:/var/log
    depends_on:
      - web

