# Generated by Django 3.1.7 on 2021-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('include', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTypes',
            fields=[
                ('lesson_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_type_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('occupation_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'occupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_num', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleCalls',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule_calls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
    ]
